{"name": "Если авторизоваться под несуществующим пользователем, запрос возвращает cообщение валидации", "status": "passed", "description": "Проверяем, что вернулся ожидаемый текст cообщения валидации", "steps": [{"name": "Логин курьером", "status": "passed", "parameters": [{"name": "login", "value": "'notexistinguser'"}, {"name": "password", "value": "'somepassword1'"}], "start": 1704136970560, "stop": 1704136971115}], "start": 1704136970560, "stop": 1704136971117, "uuid": "dcaa4cde-88f9-4613-b312-73f73fb553e5", "historyId": "eac3e98f91af8986a5c45f572e781c8c", "testCaseId": "eac3e98f91af8986a5c45f572e781c8c", "fullName": "test_courier_login.TestCourierLogin#test_unsuccessful_login_with_not_existing_credentials", "labels": [{"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-PR51OJ8"}, {"name": "thread", "value": "64268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier_login"}]}